#opencl_include_dir = '/usr/local/stream/include'
opencl_include_dir = '/usr/local/cuda/include'
#opencl_library_dir = '/usr/local/stream/lib'
opencl_library_dir = '/usr/local/cuda/lib'
#opencl_library = 'atiocl64'
opencl_library = 'OpenCL'
